### PR TITLE
Create createtables.sql

### PR DESCRIPTION
**Pull request by dr28-calvin**

### CODE REVIEW

**Comment by dr28-calvin** [comment]
Hello, @kvlinden 
This is my table creation SQL script. How does this look?

**Comment by kvlinden** [comment]
Assigning me as a reviewer generated an email, so that approach works well.  The @kvlinden message generated another, unneeded email, so you can skip that in the future.

The script has several features that I haven't used, but if they're working for you then go with them. Comments:
- I don't like commenting out the DROP TABLE. PostgresSQL has an IF EXISTS clause that's useful here.
- I upgraded to SERIAL primary keys, which is a script that auto-builds the sequence objects. I've not used the UUID type; does it auto-generated unique IDs? You'll need that for the REST POST/Create command.
- There's lots of NOT NULL constraints in there. I wonder if there would be times you'd like to use NULL values for those fields. 

For details, see https://github.com/calvin-cs262-organization/monopoly-service/blob/master/sql/monopoly.sql.

**Comment by dr28-calvin** [comment]
I will change over to using the `IF EXIST`.

UUID is a data type that is specified by IETF RFC 4122 it is a 128bit identifier designed for databases with tons of data. There are 5 ways of generating the UUID the one I chose is random. The other ways require some form of extra information. I have previously had a bad time with integers and auto incrementing. some how the id's that were generated by the database  were already used and conflicted with the new items that were getting added. Some how it didn't know where it last left off. The chance of a collision is less likely, and can be reinserted if it fails where as I had to manually go in and correct the auto incremented id number.

In theory there might be a time that NULL would be useful, but at the same time an empty string would work in most cases.

**Comment by kvlinden** [comment]
Agreed, UUIDs are good. I almost covered that pattern in class on Monday.

**Review by Nmad7 — CHANGES_REQUESTED** [review]
Nice job. This looks good for creating the table but if we aren't going to have the table populated fully by your calvin news database then we need to have some sample inserts after creating the table. Also I think it would be nice if you could just do one more slightly different query on the data than you have, just so we have more than one.

**Review by Nmad7 — APPROVED** [review]
Thanks for adding data as well.

**Pull request merged**
